import Head from "next/head";
import Cursor from "@components/molecules/CustomCursor/Cursor/Component";
import { CurrentCursorDisplay } from "@components/molecules/CustomCursor/CurrentCursorDisplay/Component";
import CursorSetter from '@components/molecules/CustomCursor/CursorSetter/Component'
import styles from './page.module.css';

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Cursor />
        <div className={styles.content}>
          {/* <h1>{currentCursor}</h1> */}
          <CurrentCursorDisplay/>
          <div className={styles.grid}>
          <CursorSetter cursor="shrink">
            <div className={styles.box}></div>
          </CursorSetter>
          <CursorSetter cursor="pill">
            <div className={styles.box}></div>
          </CursorSetter>
          <CursorSetter cursor="line">
            <div className={styles.box}></div>
          </CursorSetter>
          <CursorSetter cursor="dot" motion="snap">
            <div className={styles.box}></div>
          </CursorSetter>
          </div>
        </div>
      </main>
    </>
  );
}
